package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunCommandHelp(t *testing.T) {
	for _, arg := range []string{"-h", "--help"} {
		t.Run(arg, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer

			code := runCommand([]string{arg}, &stdout, &stderr)
			if code != 0 {
				t.Fatalf("expected exit code 0, got %d", code)
			}
			if stderr.Len() != 0 {
				t.Fatalf("expected empty stderr, got %q", stderr.String())
			}

			out := stdout.String()
			for _, snippet := range []string{
				"Usage of gen-columns:",
				"-full",
				"-output-path string",
				"-struct-path string",
			} {
				if !strings.Contains(out, snippet) {
					t.Fatalf("help output missing snippet %q\noutput:\n%s", snippet, out)
				}
			}
		})
	}
}

func TestLoadConfigDefaultsPaths(t *testing.T) {
	tmp := t.TempDir()
	tmp, err := filepath.EvalSymlinks(tmp)
	if err != nil {
		t.Fatalf("eval symlinks tmp: %v", err)
	}
	prev, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(tmp); err != nil {
		t.Fatalf("chdir tmp: %v", err)
	}
	defer func() {
		if err := os.Chdir(prev); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	}()

	cfg, err := loadConfig(nil)
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.Root != tmp {
		t.Fatalf("expected root %q, got %q", tmp, cfg.Root)
	}
	wantOutput := filepath.Join(tmp, "pkg", "model")
	if cfg.OutputPath != wantOutput {
		t.Fatalf("expected output path %q, got %q", wantOutput, cfg.OutputPath)
	}
	wantStruct := tmp
	if cfg.StructPath != wantStruct {
		t.Fatalf("expected struct path %q, got %q", wantStruct, cfg.StructPath)
	}
	if cfg.Generator != "gen-columns" {
		t.Fatalf("expected generator %q, got %q", "gen-columns", cfg.Generator)
	}
}

func TestLoadConfigResolvesStructPath(t *testing.T) {
	tmp := t.TempDir()
	tmp, err := filepath.EvalSymlinks(tmp)
	if err != nil {
		t.Fatalf("eval symlinks tmp: %v", err)
	}
	prev, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(tmp); err != nil {
		t.Fatalf("chdir tmp: %v", err)
	}
	defer func() {
		if err := os.Chdir(prev); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	}()

	cfg, err := loadConfig([]string{"--struct-path", "nested"})
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	want := filepath.Join(tmp, "nested")
	if cfg.StructPath != want {
		t.Fatalf("expected struct path %q, got %q", want, cfg.StructPath)
	}
	if cfg.Generator != "gen-columns --struct-path nested" {
		t.Fatalf("expected generator %q, got %q", "gen-columns --struct-path nested", cfg.Generator)
	}
}

func TestLoadConfigResolvesOutputPath(t *testing.T) {
	tmp := t.TempDir()
	tmp, err := filepath.EvalSymlinks(tmp)
	if err != nil {
		t.Fatalf("eval symlinks tmp: %v", err)
	}
	prev, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(tmp); err != nil {
		t.Fatalf("chdir tmp: %v", err)
	}
	defer func() {
		if err := os.Chdir(prev); err != nil {
			t.Fatalf("restore cwd: %v", err)
		}
	}()

	cfg, err := loadConfig([]string{"--output-path", "custom/model"})
	if err != nil {
		t.Fatalf("load config: %v", err)
	}

	wantOutput := filepath.Join(tmp, "custom", "model")
	if cfg.OutputPath != wantOutput {
		t.Fatalf("expected output path %q, got %q", wantOutput, cfg.OutputPath)
	}
	wantStruct := tmp
	if cfg.StructPath != wantStruct {
		t.Fatalf("expected struct path %q, got %q", wantStruct, cfg.StructPath)
	}
	if cfg.Generator != "gen-columns --output-path custom/model" {
		t.Fatalf("expected generator %q, got %q", "gen-columns --output-path custom/model", cfg.Generator)
	}
}

func TestGeneratorWritesColumns(t *testing.T) {
	tmp := t.TempDir()
	writeGeneratorFixture(t, tmp)

	if err := run(config{Root: tmp, OutputPath: filepath.Join(tmp, "pkg", "model"), StructPath: tmp}); err != nil {
		t.Fatalf("run default generator: %v", err)
	}

	if _, err := os.Stat(filepath.Join(tmp, "pkg", "model", "col", "foo.col.go")); !os.IsNotExist(err) {
		t.Fatalf("expected no per-struct file, got err = %v", err)
	}

	allContent, err := os.ReadFile(filepath.Join(tmp, "pkg", "model", "col", "col.go"))
	if err != nil {
		t.Fatalf("read all columns file: %v", err)
	}
	allStr := string(allContent)
	allSnippets := []string{
		"// Code generated by gen-columns DO NOT EDIT.",
		"// WARNING: Changes to this file may cause incorrect behavior",
		"// and will be lost if the code is regenerated",
		"// Generator:",
		"// gen-columns",
		"package col",
		"const (",
		"All  = \"*\"",
		"Id   = \"id\"",
		"Name = \"name\"",
	}
	for _, snippet := range allSnippets {
		if !strings.Contains(allStr, snippet) {
			t.Fatalf("all columns file missing snippet %q\ncontent:\n%s", snippet, allStr)
		}
	}

	idxAll := strings.Index(allStr, "All  = \"*\"")
	idxId := strings.Index(allStr, "Id   = \"id\"")
	if idxAll == -1 || idxId == -1 {
		t.Fatalf("expected All and Id constants in generated content:\n%s", allStr)
	}
	if idxAll > idxId {
		t.Fatalf("expected All constant to appear before Id\ncontent:\n%s", allStr)
	}
}

func TestGeneratorFullWritesColumns(t *testing.T) {
	tmp := t.TempDir()
	writeGeneratorFixture(t, tmp)

	if err := run(config{Root: tmp, OutputPath: filepath.Join(tmp, "pkg", "model"), StructPath: tmp, Full: true}); err != nil {
		t.Fatalf("run full generator: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmp, "pkg", "model", "dao", "foo.col.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	generated := string(content)
	wantSnippets := []string{
		"// Code generated by gen-columns DO NOT EDIT.",
		"// WARNING: Changes to this file may cause incorrect behavior",
		"// and will be lost if the code is regenerated",
		"// Generator:",
		"// gen-columns",
		"package dao",
		"var FooDao = struct {",
		"ID   string",
		"Name string",
		"ID:",
		"Name:",
	}
	for _, snippet := range wantSnippets {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated file missing snippet %q\ncontent:\n%s", snippet, generated)
		}
	}
}

func TestGeneratorRecursivelyFindsGoFiles(t *testing.T) {
	tmp := t.TempDir()
	writeGeneratorFixture(t, filepath.Join(tmp, "nested", "module"))

	if err := run(config{Root: tmp, OutputPath: filepath.Join(tmp, "pkg", "model"), StructPath: tmp}); err != nil {
		t.Fatalf("run recursive generator: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmp, "pkg", "model", "col", "col.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	generated := string(content)
	for _, snippet := range []string{"Id   = \"id\"", "Name = \"name\""} {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated file missing snippet %q\ncontent:\n%s", snippet, generated)
		}
	}
}

func TestGeneratorWritesToCustomOutputPath(t *testing.T) {
	tmp := t.TempDir()
	writeGeneratorFixture(t, filepath.Join(tmp, "source"))

	outputPath := filepath.Join(tmp, "generated", "model")
	if err := run(config{
		Root:       tmp,
		OutputPath: outputPath,
		StructPath: filepath.Join(tmp, "source"),
	}); err != nil {
		t.Fatalf("run custom output generator: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(outputPath, "col", "col.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	generated := string(content)
	for _, snippet := range []string{"Id   = \"id\"", "Name = \"name\""} {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated file missing snippet %q\ncontent:\n%s", snippet, generated)
		}
	}
}

func TestGeneratorFullWritesToCustomOutputDaoPath(t *testing.T) {
	tmp := t.TempDir()
	writeGeneratorFixture(t, filepath.Join(tmp, "source"))

	outputPath := filepath.Join(tmp, "generated", "model")
	if err := run(config{
		Root:       tmp,
		OutputPath: outputPath,
		StructPath: filepath.Join(tmp, "source"),
		Full:       true,
	}); err != nil {
		t.Fatalf("run custom full generator: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(outputPath, "dao", "foo.col.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	generated := string(content)
	for _, snippet := range []string{"package dao", "var FooDao = struct {"} {
		if !strings.Contains(generated, snippet) {
			t.Fatalf("generated file missing snippet %q\ncontent:\n%s", snippet, generated)
		}
	}
}

func TestGeneratorCollectsDBTagsFromAllStructsInFile(t *testing.T) {
	tmp := t.TempDir()
	writeMultiStructGeneratorFixture(t, tmp)

	outputPath := filepath.Join(tmp, "pkg", "model")
	if err := run(config{Root: tmp, OutputPath: outputPath, StructPath: tmp, Full: true}); err != nil {
		t.Fatalf("run generator with multiple structs: %v", err)
	}

	allContent, err := os.ReadFile(filepath.Join(outputPath, "col", "col.go"))
	if err != nil {
		t.Fatalf("read all columns file: %v", err)
	}

	allGenerated := string(allContent)
	for _, snippet := range []string{"Id   = \"id\"", "Name = \"name\"", "Code = \"code\"", "Type = \"type\""} {
		if !strings.Contains(allGenerated, snippet) {
			t.Fatalf("all columns file missing snippet %q\ncontent:\n%s", snippet, allGenerated)
		}
	}

	daoContent, err := os.ReadFile(filepath.Join(outputPath, "dao", "foo.col.go"))
	if err != nil {
		t.Fatalf("read generated dao file: %v", err)
	}

	daoGenerated := string(daoContent)
	for _, snippet := range []string{
		"var FooDao = struct {",
		"var FooFilter = struct {",
		"ID   string",
		"Name string",
		"Code string",
		"Type string",
	} {
		if !strings.Contains(daoGenerated, snippet) {
			t.Fatalf("dao columns file missing snippet %q\ncontent:\n%s", snippet, daoGenerated)
		}
	}
}

func writeGeneratorFixture(t *testing.T, tmp string) {
	t.Helper()

	daoDir := filepath.Join(tmp, "pkg", "model", "dao")
	if err := os.MkdirAll(daoDir, 0o755); err != nil {
		t.Fatalf("mkdir dao: %v", err)
	}

	src := "package dao\n\n" +
		"type FooDao struct {\n" +
		"\tID   string  `db:\"id\" json:\"id\"`\n" +
		"\tName *string `db:\"name\" json:\"name\"`\n" +
		"}\n"
	daoFile := filepath.Join(daoDir, "foo.dao.go")
	if err := os.WriteFile(daoFile, []byte(src), 0o644); err != nil {
		t.Fatalf("write dao file: %v", err)
	}
}

func writeMultiStructGeneratorFixture(t *testing.T, tmp string) {
	t.Helper()

	daoDir := filepath.Join(tmp, "pkg", "model", "dao")
	if err := os.MkdirAll(daoDir, 0o755); err != nil {
		t.Fatalf("mkdir dao: %v", err)
	}

	src := "package dao\n\n" +
		"type FooDao struct {\n" +
		"\tID   string  `db:\"id\" json:\"id\"`\n" +
		"\tName *string `db:\"name\" json:\"name\"`\n" +
		"}\n\n" +
		"type FooFilter struct {\n" +
		"\tCode string `db:\"code\" json:\"code\"`\n" +
		"\tType string `db:\"type\" json:\"type\"`\n" +
		"}\n"
	daoFile := filepath.Join(daoDir, "foo.dao.go")
	if err := os.WriteFile(daoFile, []byte(src), 0o644); err != nil {
		t.Fatalf("write dao file: %v", err)
	}
}

func TestWarnIdentifierCollisions(t *testing.T) {
	t.Run("writes warning when identifiers collide", func(t *testing.T) {
		origStderr := os.Stderr
		r, w, err := os.Pipe()
		if err != nil {
			t.Fatalf("pipe: %v", err)
		}
		os.Stderr = w
		defer func() {
			os.Stderr = origStderr
		}()

		columns := []string{"foo_bar", "foo-bar", "id"}
		warnIdentifierCollisions(columns)

		if err := w.Close(); err != nil {
			t.Fatalf("close writer: %v", err)
		}

		out, err := io.ReadAll(r)
		if err != nil {
			t.Fatalf("read stderr: %v", err)
		}

		got := string(out)
		want := "warning: pkg/model/col/col.go constant FooBar has multiple column values: foo-bar, foo_bar\n"
		if got != want {
			t.Fatalf("unexpected warning\nwant: %q\ngot:  %q", want, got)
		}
	})

	t.Run("no warning when identifiers unique", func(t *testing.T) {
		origStderr := os.Stderr
		r, w, err := os.Pipe()
		if err != nil {
			t.Fatalf("pipe: %v", err)
		}
		os.Stderr = w
		defer func() {
			os.Stderr = origStderr
		}()

		columns := []string{"foo_bar", "bar_baz"}
		warnIdentifierCollisions(columns)

		if err := w.Close(); err != nil {
			t.Fatalf("close writer: %v", err)
		}

		out, err := io.ReadAll(r)
		if err != nil {
			t.Fatalf("read stderr: %v", err)
		}
		if len(out) != 0 {
			t.Fatalf("expected no warnings, got %q", string(out))
		}
	})
}
