package shared

const (
	X_Portal       = "x_portal"
	X_PortalDomain = "x_portal_domain"
	X_PortalId     = "x_portal_id"
	X_PortalCode   = "x_portal_code"
	X_RoleId       = "x_role_id"
	X_Service      = "x_service"
	X_Controller   = "x_controller"
	X_Action       = "x_action"
	X_UserId       = "x_user_id"
	X_UserName     = "x_user_name"
	X_UserEmail    = "x_user_email"
	X_UserPhone    = "x_user_phone"
	X_Trace        = "x_trace"
	X_Slug         = "x_slug"
	X_AtClaims     = "x_at_claims"
	X_Token        = "x_token"
	X_Level        = "x_level"

	DangerouslySetColumns = "columns"
	OmitTotal             = "omit_total"
	AllData               = "all_data"
	OmitDetails           = "omit_details"
	OmitPassword          = "omit_password"
	ExpandAccess          = "expand_access"
	ExceptionSource       = "exception.source"
	ExceptionStackFrames  = "exception.stack_frames"
	HardDelete            = "hard_delete"
	SoftDelete            = "soft_delete"
	EmptyUuid             = "00000000-0000-0000-0000-000000000000"
	TrxInstance           = "trx_instance"
	TaskInstance          = "task_instance"
	DisableAutoCommit     = "disable_auto_commit"
	AllowDuplicate        = "allow_duplicate"
	TrueLogDate           = "true_logdate"
	ExecuteIn             = "execute_in"
	Default               = "default"
	Wsk                   = "wsk"
	SqlSuffix             = "sql_suffix"

	SceneAPI            = "api"
	SceneHTMX           = "htmx"
	SceneLogin          = "Login"
	SceneForgotPassword = "ForgotPassword"
	SceneCreate         = "Create"
	SceneEdit           = "Edit"
	SceneDelete         = "Delete"
	SceneView           = "View"
	ScenePublish        = "Publish"
	SceneUnpublish      = "Unpublish"
)
