name: CI

on:
  push:
    branches: [ dev, qa, main ]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Build
        run: |
          go build \
            -ldflags=" \
              -X 'github.com/0xelden/common-libs-go/cli.Commit=${GITHUB_SHA::7}' \
              -X 'github.com/0xelden/common-libs-go/cli.Created=$(date -R)' \
              -X 'github.com/0xelden/common-libs-go/cli.Build=$(uname -nmr)' \
              -X 'github.com/0xelden/common-libs-go/cli.Version=${GITHUB_REF_NAME}' "
